steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/geargrab-svelte:$COMMIT_SHA', '.']
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/geargrab-svelte:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'geargrab-svelte'
      - '--image=gcr.io/$PROJECT_ID/geargrab-svelte:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--max-instances=100'
      - '--min-instances=1'
      - '--concurrency=1000'
      - '--timeout=300'
      - '--execution-environment=gen2'
      - '--cpu-throttling=false'
      - '--set-env-vars=NODE_ENV=production,BASE44_SERVER_URL=https://base44.app,BASE44_ENV=prod'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/geargrab-svelte:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
