steps:
  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/geargrab-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/geargrab-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'geargrab-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/geargrab-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=${_DATABASE_URL},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_ADMIN_CLIENT_EMAIL=${_FIREBASE_ADMIN_CLIENT_EMAIL},FIREBASE_ADMIN_PRIVATE_KEY=${_FIREBASE_ADMIN_PRIVATE_KEY}'
images:
  - 'gcr.io/$PROJECT_ID/geargrab-app'
