name: Reliable Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
      force_rebuild:
        description: 'Force rebuild without cache'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - latest-version

env:
  PROJECT_ID: geargrabco
  SERVICE_NAME: geargrab
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: ☁️ Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔧 Install dependencies
        run: |
          echo "Installing dependencies..."
          npm cache clean --force
          npm install --no-audit --no-fund
          echo "Dependencies installed successfully"

      - name: 🏗️ Build application
        run: |
          echo "Building application..."
          export NODE_ENV=production
          export VITE_FIREBASE_API_KEY="${{ secrets.VITE_FIREBASE_API_KEY || 'AIzaSyANV1v2FhD2ktXxBUsfGrDm9442dGGCuYs' }}"
          export VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.VITE_FIREBASE_AUTH_DOMAIN || 'geargrabco.firebaseapp.com' }}"
          export VITE_FIREBASE_PROJECT_ID="${{ secrets.VITE_FIREBASE_PROJECT_ID || 'geargrabco' }}"
          export VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.VITE_FIREBASE_STORAGE_BUCKET || 'geargrabco.firebasestorage.app' }}"
          export VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID || '227444442028' }}"
          export VITE_FIREBASE_APP_ID="${{ secrets.VITE_FIREBASE_APP_ID || '1:227444442028:web:6eeaed1e136d07f5b73009' }}"
          export VITE_STRIPE_PUBLISHABLE_KEY="${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY || 'pk_live_51RZXbxBfCDZxMJmHHUzHwNJq1gNdpcMjp4kAJK28n8d5kTXPhI4pnptDiLJmyHybfhJzY7vIVZOaNrzJClCkY3vS00tMlh4lyZ' }}"
          npm run build
          echo "Build completed successfully"
          ls -la build/

      - name: ☁️ Deploy to Cloud Run (Environment Variables Only)
        run: |
          echo "Updating Cloud Run service with new environment variables..."

          # Just update the existing service with new environment variables
          # This avoids Docker/Artifact Registry issues entirely
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 10 \
            --timeout 300 \
            --concurrency 80 \
            --set-env-vars NODE_ENV=production \
            --set-env-vars PORT=8080 \
            --set-env-vars HOST=0.0.0.0 \
            --set-env-vars VITE_USE_EMULATORS=false \
            --set-env-vars VITE_APP_URL=https://geargrab.co \
            --set-env-vars FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            --set-env-vars FIREBASE_ADMIN_CLIENT_EMAIL=firebase-adminsdk-fbsvc@geargrabco.iam.gserviceaccount.com \
            --set-env-vars FIREBASE_ADMIN_PRIVATE_KEY="${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}" \
            --set-env-vars STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --set-env-vars VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
            --set-env-vars VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }} \
            --set-env-vars VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }} \
            --set-env-vars VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }} \
            --set-env-vars VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} \
            --set-env-vars VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }} \
            --set-env-vars VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }} \
            --quiet

          echo "✅ Cloud Run deployment completed!"

      - name: 🔍 Test deployment
        run: |
          echo "Testing deployment..."
          sleep 30

          # Get the service URL
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format='value(status.url)')
          echo "Service URL: $SERVICE_URL"

          # Test the deployment
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
          echo "HTTP response code: $HTTP_CODE"

          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Deployment test PASSED - Facebook login is now live!"
            echo "🎉 Visit: $SERVICE_URL"
          else
            echo "⚠️ Deployment test warning - received status code: $HTTP_CODE"
            echo "Service may still be starting up..."
          fi

      - name: 🎯 Deployment Summary
        run: |
          echo "🚀 DEPLOYMENT COMPLETE!"
          echo "📱 Facebook login should now show 'Continue with Facebook'"
          echo "🌐 Live site: https://geargrab.co"
          echo "⏰ Deployed at: $(date)"
          echo "📝 Commit: ${{ github.sha }}"
